"""Dependency-Check input preparation and coverage verification."""

from __future__ import annotations

import json

from scripts import depcheck_input

LOCK = """\
#
# This file is autogenerated by pip-compile
#
annotated-types==0.8.0 \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
    # via pydantic
PyJWT==2.3.0 \\
    --hash=sha256:cccc
    # via -r requirements.in
typing_extensions==4.16.0 ; python_version < "3.15" \\
    --hash=sha256:dddd
"""


def _report(*purls: str) -> dict:
    return {"dependencies": [{"fileName": "requirements.txt", "packages": [{"id": p}]} for p in purls]}


def test_extract_keeps_only_pins(tmp_path):
    lock = tmp_path / "requirements.txt"
    lock.write_text(LOCK)
    assert depcheck_input.extract([lock]) == ["annotated-types==0.8.0", "PyJWT==2.3.0", "typing_extensions==4.16.0"]


def test_verify_full_coverage_with_name_normalisation():
    pins = ["PyJWT==2.3.0", "typing_extensions==4.16.0"]
    report = _report("pkg:pypi/pyjwt@2.3.0", "pkg:pypi/typing-extensions@4.16.0")
    assert depcheck_input.verify(pins, report) == []


def test_verify_detects_unparsed_lockfile_lines():
    # What Dependency-Check produced for the raw lockfile: the whole line is the "name".
    report = _report("pkg:pypi/pyjwt%3D%3D2.3.0%20%5C", "pkg:pypi/%20%20%20%20%23%20via%20pydantic")
    assert depcheck_input.verify(["PyJWT==2.3.0"], report) == ["PyJWT==2.3.0"]


def test_cli_roundtrip(tmp_path):
    lock = tmp_path / "requirements.txt"
    lock.write_text(LOCK)
    pins = tmp_path / "pins.txt"
    assert depcheck_input.main(["extract", str(lock), "-o", str(pins)]) == 0
    report = tmp_path / "report.json"
    report.write_text(json.dumps(_report("pkg:pypi/annotated-types@0.8.0", "pkg:pypi/pyjwt@2.3.0")))
    assert depcheck_input.main(["verify", str(pins), str(report)]) == 1  # typing_extensions missing
    report.write_text(
        json.dumps(
            _report("pkg:pypi/annotated-types@0.8.0", "pkg:pypi/pyjwt@2.3.0", "pkg:pypi/typing-extensions@4.16.0")
        )
    )
    assert depcheck_input.main(["verify", str(pins), str(report)]) == 0
